### PR TITLE
Major update and fixes

### PR DESCRIPTION
**Pull request by ladas-larry**
- hot loading functionality fixed
- updated dependencies
- project structure changed for better fit with official docs: https://webpack.js.org/guides/hmr-react/#webpack-configuration

### CODE REVIEW

**Comment by Trendy** [comment]
Was checking out this change locally, and I can't seem to load anything. Not sure if it's related to the removal of the `index.html` file just yet, I'll have more time to check it out tomorrow. Are you experiencing this locally as well?

**Comment by ladas-larry** [comment]
@Trendy It works really fine for mine. What is actually the problem?

screen shot 2017-05-29 at 10 23 27

**Comment by Trendy** [comment]
Responds with a 404 for me.

Here's my setup, not sure if it matters:

Node - 6.9.1
NPM - 3.10.10
WebPack - 2.6.1
TypeScript 2.3.3

screen shot 2017-05-29 at 2 16 02 pm

**Comment by Glavin001** [comment]
This is what I see: 
image

**Review by Glavin001 — CHANGES_REQUESTED** [review]
In its current state, a fresh install and build does not work. Please fix and we can review again. Thank you!

**Comment by Glavin001** [comment]
I've made a new PR with some changes, including updating dependencies and improving the build process (allow for builds which can be served statically, without webpack-dev-server). Please take a look and let me know if it is good for merging: https://github.com/Glavin001/react-hot-ts/pull/8
Thanks!

**Comment by ladas-larry** [comment]
fixed! dist folder should not be ignored

**Comment by Glavin001** [comment]
The `dist/` folder, **should** be ignored 😛 . I think there is still something wrong.
We should be able to delete the `dist/` folder at any time and rebuild from scratch.

**Comment by ladas-larry** [comment]
Depends how much you want to be consistent with official documentation, up to you.

**Comment by Glavin001** [comment]
The official documentation recommends committing the `dist/` folder, including generated files, to Git? Well then... looks like we will have to deviate 😛 . I appreciate you looking into this and clarifying.

**Comment by Glavin001** [comment]
Actually, it is only `dist/index.html` not all of `dist/`, which is what this PR currently suggests. I would expect to see the following in the `.gitignore` instead:

```
dist/*
dist/index.html
```

See https://stackoverflow.com/a/16318111/2578205 for details.

This would be something I could accept. However, I have already opted to use [html-webpack-plugin](https://github.com/jantimon/html-webpack-plugin) instead since it provides more flexibility in long run. This has since been merged.

Take a look at the current state of this repository and see what changes you still would like to make. I tried to update some things you did, such as dependencies.

Thank you for contributing! 😃

**Comment by Trendy** [comment]
@Dharmoslap The official documentation for HMR/React mentions them choosing to include the `index.html` file in the `/dist` folder, so that things would run properly. I don't think that it was meant to be a requirement of code folder structure. 

Personally, I'd include `index.html` outside of the `/dist` folder, which could potentially include files built with modifications not relevant to this project. I think that @Glavin001 did this in #8 and in the original project.

**Comment by ladas-larry** [comment]
@Trendy Of course I got that, but that means that anybody who starts with official documentation and later would move to TS will have to change folder structure just to try to follow this demo, which is dumb. As I  understood the purpose of this repo was not to give you the ideal folder structure for your project (neither to make you switch to use html-webpack-plugin), but rather to be the fastest way to get react hot reload working with TS. I'm closing this, thanks.

**Pull request closed without merging**
